print('a=')
a = input()
print('b=')
b = input()
print('c=')
c = input()
a = int(a)
b = int(b)
c = int(c)
d = int((a**2+b**2)/(3*b-4))
e = int(4*c**5/6)
print('Целая часть:')
print(d//e)
print('Остаток от деления:')
print(d % e)
